# Generated by Django 6.0.2 on 2026-02-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dividas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_parcela', models.IntegerField()),
                ('data', models.DateField()),
            ],
        ),
    ]
