# Generated by Django 6.0.2 on 2026-03-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dividas',
            old_name='valor_parcela',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='dividas',
            name='total_parcela',
        ),
        migrations.AddField(
            model_name='dividas',
            name='categoria',
            field=models.CharField(choices=[('Moradia', 'Moradia'), ('Contas', 'Contas'), ('Mercados', 'Mercados'), ('Transporte', 'Transporte'), ('Saúde', 'Saúde'), ('Lazer', 'Lazer'), ('Restaurante', 'Restaurante'), ('Compras', 'Compras'), ('Assinatura', 'Assinatura'), ('Educação', 'Educação'), ('Imprevisto', 'Imprevisto')], default='Lazer'),
        ),
    ]
