# Generated by Django 6.0.2 on 2026-02-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('categoria', models.CharField(choices=[('Moradia', 'Moradia'), ('Contas', 'Contas'), ('Saúde', 'Saúde'), ('Assinaturas', 'Assinaturas'), ('Educação', 'Educação'), ('Transporte', 'Transporte')], default='Assinaturas', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
