# Generated by Django 6.0.2 on 2026-02-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixos',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='fixos',
            name='categoria',
            field=models.CharField(choices=[('Moradia', 'Moradia'), ('Contas', 'Contas'), ('Saúde', 'Saúde'), ('Assinaturas', 'Assinaturas'), ('Educação', 'Educação'), ('Transporte', 'Transporte')], default='Assinatura', max_length=20),
        ),
    ]
