# Generated by Django 6.0.2 on 2026-02-23 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartao',
        ),
        migrations.DeleteModel(
            name='Fixos',
        ),
    ]
