# Generated by Django 6.0.2 on 2026-02-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gasto',
            new_name='Gastos',
        ),
    ]
