# Generated by Django 6.0.2 on 2026-02-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_delete_cartao_delete_fixos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caixinhas',
        ),
        migrations.DeleteModel(
            name='Dividas',
        ),
    ]
