# Generated by Django 6.0.2 on 2026-02-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_cartao_fixos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixinhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=10)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guardado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dividas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='fixos',
            name='tipo',
            field=models.CharField(choices=[('assinatura', 'Assinatura'), ('conta', 'Conta')], default='conta'),
        ),
    ]
