# Generated by Django 6.0.2 on 2026-02-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_caixinhas_dividas_alter_fixos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividas',
            name='total_parcela',
            field=models.IntegerField(max_length=10),
        ),
    ]
