# Generated by Django 6.0.2 on 2026-02-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_dividas_total_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividas',
            name='total_parcela',
            field=models.IntegerField(),
        ),
    ]
