# Generated by Django 6.0.2 on 2026-02-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_alter_dividas_total_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividas',
            name='total_parcela',
            field=models.IntegerField(max_length=10),
        ),
    ]
