# Generated by Django 6.0.2 on 2026-02-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('registro', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Pix', 'Pix'), ('Débito', 'Débito'), ('Crédito', 'Crédito'), ('VR', 'VR'), ('VA', 'VA')], default='Dinheiro', max_length=20)),
                ('categoria', models.CharField(choices=[('Moradia', 'Moradia'), ('Contas', 'Contas'), ('Mercados', 'Mercados'), ('Transporte', 'Transporte'), ('Saúde', 'Saúde'), ('Lazer', 'Lazer'), ('Restaurante', 'Restaurante'), ('Compras', 'Compras'), ('Assinatura', 'Assinatura'), ('Educação', 'Educação'), ('Imprevisto', 'Imprevisto')], default='Lazer', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
