# Generated by Django 6.0.2 on 2026-02-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='categoria',
            field=models.CharField(choices=[('Moradia', 'Moradia'), ('Contas', 'Contas'), ('Mercados', 'Mercados'), ('Transporte', 'Transporte'), ('Saúde', 'Saúde'), ('Lazer', 'Lazer'), ('Restaurante', 'Restaurante'), ('Compras', 'Compras'), ('Assinatura', 'Assinatura'), ('Educação', 'Educação'), ('Imprevisto', 'Imprevisto')], default='Lazer'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='tipo',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Pix', 'Pix'), ('Débito', 'Débito'), ('Crédito', 'Crédito'), ('VR', 'VR'), ('VA', 'VA')], default='Dinheiro'),
        ),
    ]
